### ISSUE TITLE
Transaction Domain Tag

### ISSUE THREAD

**Issue by kaliweh-circle** [onflow/flow-jvm-sdk#11]
Add support for the flow transaction domain tag. [ref](https://github.com/onflow/flow-js-sdk/blob/6e2cc52d1cc87cfdf417f74ef131764d91f7d6ef/packages/sdk/CHANGELOG.md#0046-alpha1---2021-05-05)

**Comment by psiemens** [comment]
@briandilley This change doesn't require an updated `org.onflow:flow` artifact, so you should be good with the current one.

Unfortunately we don't have docs up for this yet (sorry about that), but here's how domain tags work:

The domain tag is prepended to the signable message _before_ hashing to differentiate transaction signatures from other arbitrary signatures. We're introducing functionality similar to web3's `personalSign` method, but in order to do this safely, we need to make sure that signers and verifiers can differentiate between transaction signatures and "user" signatures. This is to protect the user from being tricked into signing a transaction disguised as an arbitrary payload.

- The transaction domain tag is defined here in the Go SDK: https://github.com/onflow/flow-go-sdk/blob/master/sign.go#L29-L32
- The key thing to note is that it's right-padded with zero bytes to a total length of 32 bytes.
- You'll basically want to prepend the buffer that you send into the `Signer.sign` method here: https://github.com/onflow/flow-jvm-sdk/blob/main/src/main/kotlin/org/onflow/sdk/models.kt#L409

```
SIGNATURE = SIGN( HASH( DOMAIN_TAG + MESSAGE ) )
```

You can test this with the latest emulator release: https://github.com/onflow/flow-emulator/releases/tag/v0.20.2

**Comment by briandilley** [comment]
seems easy enough, will take a look at it tonight.
